<?php

use App\User;
use App\Post;
use App\Tag;
use App\Comment;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->call(UsersTableSeeder::class);
        $this->call(PostsTableSeeder::class);
        $this->call(TagsTableSeeder::class);
        $this->call(CommentsTableSeeder::class);
    }
}

class UsersTableSeeder extends Seeder 
{
    public function run() 
    {
        DB::table('users')->delete();

        User::create(
        [
            'name'      => 'Seán',
            'email'     => 'seanbickmore@icloud.com',
            'password'  => Hash::make('tester'),
            'bio'       => 'Welcome to Reflux, my fourth year Cyber Security project!'
        ]);

        User::create(
        [
            'name'      => 'Naxes',
            'email'     => 'naxes@example.com',
            'password'  => Hash::make('tester')
        ]);        
    }
}

class PostsTableSeeder extends Seeder 
{
    public function run()
    {
        DB::table('posts')->delete();

        Post::create(
        [
            'title'     => 'HTML',
            'body'      => '<p>This is a post generated by <b>seeding</b> to populate the site.</p>
                            <pre class="language-markup"><code>Markup Post!</code></pre>',
            'score'     => 1250,  
            'user_id'   => 1
        ]);

        Post::create(
        [
            'title'     => 'CSS',
            'body'      => '<p>This is a post generated by <b>seeding</b> to populate the site.</p>
                            <pre class="language-markup"><code>CSS Post!</code></pre>',
            'score'     => 671,  
            'user_id'   => 2
        ]);

        Post::create(
        [
            'title'     => 'JavaScript',
            'body'      => '<p>This is a post generated by <b>seeding</b> to populate the site.</p>
                            <pre class="language-markup"><code>JavaScript Post!</code></pre>',
            'score'     => 1500,  
            'user_id'   => 1
        ]);

        Post::create(
        [
            'title'     => 'PHP',
            'body'      => '<p>This is a post generated by <b>seeding</b> to populate the site.</p>
                            <pre class="language-markup"><code>PHP Post!</code></pre>',
            'score'     => 2350,  
            'user_id'   => 2
        ]);

        Post::create(
        [
            'title'     => 'Java',
            'body'      => '<p>This is a post generated by <b>seeding</b> to populate the site.</p>
                            <pre class="language-markup"><code>Java Post!</code></pre>',
            'score'     => 436,  
            'user_id'   => 1
        ]);

        Post::create(
        [
            'title'     => 'Git',
            'body'      => '<p>This is a post generated by <b>seeding</b> to populate the site.</p>
                            <pre class="language-markup"><code>Git Post!</code></pre>',
            'score'     => 1347,  
            'user_id'   => 2
        ]);

        Post::create(
        [
            'title'     => 'Ruby',
            'body'      => '<p>This is a post generated by <b>seeding</b> to populate the site.</p>
                            <pre class="language-markup"><code>Ruby Post!</code></pre>',
            'score'     => 781,  
            'user_id'   => 1
        ]);

        Post::create(
        [
            'title'     => 'Python',
            'body'      => '<p>This is a post generated by <b>seeding</b> to populate the site.</p>
                            <pre class="language-markup"><code>Python Post!</code></pre>',
            'score'     => 229,  
            'user_id'   => 2
        ]);

        Post::create(
        [
            'title'     => 'C#',
            'body'      => '<p>This is a post generated by <b>seeding</b> to populate the site.</p>
                            <pre class="language-markup"><code>C# Post!</code></pre>',
            'score'     => 404,  
            'user_id'   => 1
        ]);

        Post::create(
        [
            'title'     => 'Objective-C',
            'body'      => '<p>This is a post generated by <b>seeding</b> to populate the site.</p>
                            <pre class="language-markup"><code>Objective-C Post!</code></pre>',
            'score'     => 515,  
            'user_id'   => 2
        ]);

        Post::create(
        [
            'title'     => 'Perl',
            'body'      => '<p>This is a post generated by <b>seeding</b> to populate the site.</p>
                            <pre class="language-markup"><code>Perl Post!</code></pre>',
            'score'     => 256,  
            'user_id'   => 1
        ]);

        Post::create(
        [
            'title'     => 'JSON',
            'body'      => '<p>This is a post generated by <b>seeding</b> to populate the site.</p>
                            <pre class="language-markup"><code>JSON Post!</code></pre>',
            'score'     => 951,  
            'user_id'   => 2
        ]);
    }
}

class TagsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('tags')->delete();

        Tag::create(
        [
            'post_id' => 1,
            'name'    => 'HTML/XML'
        ]);

        Tag::create(
        [
            'post_id' => 2,
            'name'    => 'CSS'
        ]);

        Tag::create(
        [
            'post_id' => 3,
            'name'    => 'JavaScript'
        ]);

        Tag::create(
        [
            'post_id' => 4,
            'name'    => 'PHP'
        ]);

        Tag::create(
        [
            'post_id' => 5,
            'name'    => 'Java'
        ]);

        Tag::create(
        [
            'post_id' => 6,
            'name'    => 'Git'
        ]);

        Tag::create(
        [
            'post_id' => 7,
            'name'    => 'Ruby'
        ]);

        Tag::create(
        [
            'post_id' => 8,
            'name'    => 'Python'
        ]);

        Tag::create(
        [
            'post_id' => 9,
            'name'    => 'C#'
        ]);

        Tag::create(
        [
            'post_id' => 10,
            'name'    => 'Objective-C'
        ]);

        Tag::create(
        [
            'post_id' => 11,
            'name'    => 'Perl'
        ]);

        Tag::create(
        [
            'post_id' => 12,
            'name'    => 'JSON'
        ]);
    }
}

class CommentsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('comments')->delete();

        Comment::create(
        [
            'user_id' => 1,
            'post_id' => 1,            
            'comment' => 'This is a parent comment.'
        ]);

        Comment::create(
        [
            'user_id'   => 2,
            'post_id'   => 1,
            'parent_id' => 1,           
            'comment'   => 'This is a child comment.'
        ]);

        Comment::create(
        [
            'user_id' => 1,
            'post_id' => 1,            
            'comment' => 'This is another parent comment.'
        ]);
    }
}


